### ISSUE TITLE
Group: Calender issue

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#228]
The calender in groups is found on the bottom of groups between "write" and the menu button: https://projects.invisionapp.com/d/#/console/12489615/265214331/preview

- When pressing any of the dates a new page opens, with the date chosen _slided_ to:
https://projects.invisionapp.com/d/#/console/12489615/277358311/comments

Check of this list when making the features:

- [x] The top date changes when scrolling
- [x] The participant can scroll either way; backward or forward
- [x]  The calender can be opened from the bottom again
- [x] Pink ball next to offered rides show the amount of seats offered

**Comment by MattiasJay** [comment]
We have a problem. When multiple rides are added in a group or _to_ a group (via the other way) they are not all seen in the group calendar. @shresthaKiran @anjesh @anjhero

**Comment by MattiasJay** [comment]
Since the latest update the calendars in groups start on 2014 and not on 2018, @anjhero @anjesh @shresthaKiran .

**Comment by shresthaKiran** [comment]
This issue has been resolved.

**Comment by MattiasJay** [comment]
The calendar still doesn't work as according to specifications from February 5th above. 

1) When pressing a date the new page should open and slide to the selected date. In the current build, in Test Flight on August 26th, you are still directed to 2014 (using the largest group, "Sthlm - GBG", as reference and example).

2) Calender design is still wrong.

3) The top date should change, it doesn't. 

And as a note: right now the dates overlaps and breaks design when scrolling on iOS.

@anjhero @anjesh @shresthaKiran

**Comment by shresthaKiran** [comment]
Referenced in #519

**Comment by MattiasJay** [comment]
In the current build (Test FLight) the above is still wrong, do you mean that you want to close this issue and continue working with it in issue #519 instead @shresthaKiran @anjesh @anjhero ?

**Comment by shresthaKiran** [comment]
Yes, we are grouping the issues so that we can track the issues properly. @MattiasJay

**Comment by anjesh** [comment]
@MattiasJay as Kiran mentioned we are sorting the issues. Issue of same feature like experience, feed are spread in number of issues, making it difficult to look at these issues and to work on feature. we are trying to group these same feature issues in one issue, that would help us to focus and would be easy to go through the issue list. I am still closing this issue and in https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/519
 we still need to add text for what you asked and for other issues as well. 

Thank you for understanding.
