### ISSUE TITLE
Can't select time when searching on Search. It should be a slider, according to design.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#486]

**Comment by anjhero** [comment]
@MattiasJay If we implement the slider that's on the design, users won't be able to choose rides for more than one date.  Do we want this?

**Comment by shresthaKiran** [comment]
This issue has been resolved.

**Comment by MattiasJay** [comment]
This is still wrong @anjhero @anjesh @shresthaKiran : 

the current slider does not have the ability to choose "all dates" again, as the design. How can a partcipant come back to selecting all dates? Right now the participant get stuck in choosing specific date.

**Comment by shresthaKiran** [comment]
When a participant has selected date, then (x) icon is seen left of **Change** button. Clicking (x) icon will remove the selected date and 'All dates and times' will be the default option.
@MattiasJay

**Comment by MattiasJay** [comment]
Hi again @shresthaKiran . We have now tested this and even if I congratulate you on you job, it still is a bit unclear. The original design is clearer and would be preferred.
